// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqSyidAycqM0Jg7UOIaFq27MaassXZgY',
    appId: '1:421583588543:web:f746b54f20374e54c64a0a',
    messagingSenderId: '421583588543',
    projectId: 'agrihive-c8f6b',
    authDomain: 'agrihive-c8f6b.firebaseapp.com',
    storageBucket: 'agrihive-c8f6b.firebasestorage.app',
    measurementId: 'G-ZRQTLK3NFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhh2Yl7HBi7AzV6PS-mJ4atKen6h0Kzs',
    appId: '1:421583588543:android:3c2a97bc404b5ad9c64a0a',
    messagingSenderId: '421583588543',
    projectId: 'agrihive-c8f6b',
    storageBucket: 'agrihive-c8f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDayIiCgKXNO2nWtgKH1_fGxDnB8eofa0',
    appId: '1:421583588543:ios:7c66816d079de298c64a0a',
    messagingSenderId: '421583588543',
    projectId: 'agrihive-c8f6b',
    storageBucket: 'agrihive-c8f6b.firebasestorage.app',
    iosBundleId: 'com.example.agrihive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDayIiCgKXNO2nWtgKH1_fGxDnB8eofa0',
    appId: '1:421583588543:ios:7c66816d079de298c64a0a',
    messagingSenderId: '421583588543',
    projectId: 'agrihive-c8f6b',
    storageBucket: 'agrihive-c8f6b.firebasestorage.app',
    iosBundleId: 'com.example.agrihive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTqSyidAycqM0Jg7UOIaFq27MaassXZgY',
    appId: '1:421583588543:web:5298ad35cda34ae1c64a0a',
    messagingSenderId: '421583588543',
    projectId: 'agrihive-c8f6b',
    authDomain: 'agrihive-c8f6b.firebaseapp.com',
    storageBucket: 'agrihive-c8f6b.firebasestorage.app',
    measurementId: 'G-NJQCGDF8X1',
  );
}
